//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vF3D.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("vF3D.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contiene Fonet, http://fonet.codeplex.com/
        ///Contiene CsvHelper, http://joshclose.github.io/CsvHelper/
        ///Usa gridforms, http://kumailht.com/gridforms/
        ///Usa jQuery, http://jquery.com/
        ///Some icons by Yusuke Kamiyamane. Licensed under a Creative Commons Attribution 3.0 License..
        /// </summary>
        internal static string Attributions {
            get {
                return ResourceManager.GetString("Attributions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;xsl:stylesheet
        ///	version=&quot;1.1&quot;
        ///	xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; xmlns:vf3d=&quot;urn:vf3d&quot;&gt;
        ///  &lt;xsl:output method=&quot;html&quot; /&gt;
        ///
        ///  &lt;xsl:template match=&quot;/&quot;&gt;
        ///    &lt;xsl:apply-templates/&gt;
        ///  &lt;/xsl:template&gt;
        ///
        ///  &lt;xsl:template match=&quot;modello_3d-xml&quot;&gt;
        ///    &lt;html&gt;
        ///      &lt;head&gt;
        ///        &lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot; /&gt;
        ///        &lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;http://kumailht.com/gridforms/gridforms/gridforms.css&quot;/&gt;
        ///        &lt;script type=&quot;text/javascript&quot; src=&quot;https:/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string F3D_1_0 {
            get {
                return ResourceManager.GetString("F3D_1_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;xsl:stylesheet version=&quot;2.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; xmlns:fo=&quot;http://www.w3.org/1999/XSL/Format&quot; xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot; xmlns:vf3d=&quot;urn:vf3d&quot;&gt;
        ///  &lt;xsl:template match=&quot;/&quot;&gt;
        ///    &lt;fo:root xmlns:fo=&quot;http://www.w3.org/1999/XSL/Format&quot;&gt;
        ///      &lt;fo:layout-master-set&gt;
        ///        &lt;fo:simple-page-master master-name=&quot;A4&quot;
        ///                      page-height=&quot;29.7cm&quot;
        ///                      page-width=&quot;21cm&quot;
        ///                      margin-top=&quot;1cm [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string F3D_FO {
            get {
                return ResourceManager.GetString("F3D_FO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.istat.it/storage/codici-unita-amministrative/elenco-comuni-italiani.csv.
        /// </summary>
        internal static string ISTATPermalink {
            get {
                return ResourceManager.GetString("ISTATPermalink", resourceCulture);
            }
        }
    }
}
